export const FLAPPY_CONFIG = Object.freeze({
  birdX: 22,
  birdRadius: 2.7,
  courseRoundCount: 5,
  gravity: 48,
  flapVelocity: -18,
  pipeWidth: 10,
  gapHeight: 29,
  pipeSpeed: 20,
  courseSpeedIncreasePerRound: 0.6,
  endlessDifficultyStepMs: 45_000,
  endlessSpeedIncreaseStep: 0.2,
  maxPipeSpeed: 23.2,
  firstPipeX: 82,
  pipeSpacing: 48,
  initialLives: 2,
  recoverySeconds: 1.2,
  roundDurationMs: 90_000,
  shieldChargePerGate: 4,
  simulationTickMs: 20,
});
